### ISSUE TITLE
Json items stack on 3742 

### ISSUE THREAD

**Issue by bayaroch** [natanelia/gsmarena-scraper#1]
Its working well til 3742 item. I tried running script several times but its not getting more than 3742. In console there is still pharsin urls till 10.000 or so but no json. Sometimes getting Unhandled rejection Error: EMFILE, open 'c:\GIT\gsmarena-scraper\scrapped\Yezz Andy 4.5EL LTE.json' this error and scripts stops sometimes wont.

**Comment by bayaroch** [comment]
its strange i changed url to http://localhost:5555/files?pageLimit=0&verbose=0 then its started crawling more urls now i have 7912 items

**Comment by natanelia** [comment]
EMFILE means too much files are opened asynchronously. It should mean a bug in reading or writing the JSON file. Thanks for reporting, I will check it as soon as I have time.

Meanwhile, re-scraping continuously should help you get up to all items. The script should automatically skip previously scraped pages.

**Comment by natanelia** [comment]
As this problem has not surfaced again in the latest commit, I am marking this closed.
Thanks for reporting.
