### ISSUE TITLE
How do I know when the script is finished?

### ISSUE THREAD

**Issue by psycholyzern** [natanelia/gsmarena-scraper#2]
Is this image showing the script finished?
![](http://i.imgur.com/u4O8qP7.png)
 
Because at the end, there is an error.

I also got ```missing callback error: ENOENT```

I ran the script many tines and it skipped some but looks like it started to crawl again on the same phone (or am I misunderstood?)
On the image above is the 2nd time I ran the script.

**Comment by natanelia** [comment]
1. "Done" means it should have been finished.
2. As I've stated here, https://github.com/natanelia/gsmarena-scraper/issues/1#issuecomment-202225324, there should be a bug in file reading/writing. Meanwhile, you can do recrawling.
3. About `ENOENT`, it should be another bug. Thanks for reporting :)
4. To cache crawled items manually, you can run `/cache`. Sometimes the process is bugged and it stops before it automatically cache items. I will add this to the readme, thanks.

**Comment by psycholyzern** [comment]
Hi, thanks for the reply :)
Can I know if you will include a feature that can insert all data into sql db, or at least into a text format that can be imported into db later?

**Comment by psycholyzern** [comment]
I realized that the ENOENT came out on phone with slash in its name

Some of them:

```
fs: missing callback Error: ENOENT, open 'scrapped/NEC e540/N411i.json'
fs: missing callback Error: ENOENT, open 'scrapped/NEC e949/L1.json'
```

**Comment by psycholyzern** [comment]
And I have only 3755 files in folder scrapped. 
I used advance search in gsmarena and it said 7461 results found, which I believe the total device it has.
I ran ```npm start``` around 10 times, maybe more. But last tine I checked, only have 3755 devices in scrapped folder.

**Comment by nautical** [comment]
If you go to this page http://www.gsmarena.com/makers.php3 and enter this in console you will get the total number of devices listed on it ( which is around 8055 as of today ) .

$("td").text().match(/\(([^)]+)\)/g).map(function(o){return parseInt(o.substring(1, o.length - 1)) }).reduce((a, b) => a + b, 0);

**Comment by natanelia** [comment]
The `ENOENT` bug should have been solved in https://github.com/natanelia/gsmarena-scraper/pull/3.
As of today, I've just push out reliability update with recaching in https://github.com/natanelia/gsmarena-scraper/commit/de0daf26f855406c432e0c812e7df9039d0a243d.
It seems to have solved many random terminating problem, but not all. If you are in slow connection, it will still randomly terminate.
Whenever scraping seems to be stopped, you can just restart it now, as it will re-cache automatically (10s).

**Comment by bayaroch** [comment]
http://localhost:5555/files?pageLimit=1&verbose=1 i changed url paramemter to  http://localhost:5555/files?pageLimit=1&verbose=0 and its crawling all of them. Also try running script couple of times i have 8000+ models atm

**Comment by nautical** [comment]
Same here was able to fetch > 8000 ( 8005 ) in one run but not all 8055 , they block the ip address ( after multiple abuses , if some issue occurs make sure at least website is opening in browser ) and tor network ( always ) . Changing IP via other means might be required to fetch all .

Done also comes when the IP has been blocked .

**Comment by mastershaig** [comment]
I want to scrape all devices from GSMARENA. I go to page http://localhost:5555/files?&verbose=1
and it scrapes only 4476 devices. But there are 8419 devices in site now. Am I opening localhost:5555 with right parameters? What is verbose and pageLimit ? Can someone explain it please ?

**Comment by natanelia** [comment]
@mastershaig the script is not designed to be threaded with multiple IP addresses. As you have read, gsmarena implements Denial of Service (DOS) protection that automatically blocks IP if it detects bot behavior, which is reflected by the script. Therefore, the script can't continue scraping when it is blocked. You can throttle your connection to scrap all devices at once, or run the script multiple times.

**verbose**, means script prints all processes it is currently doing at the moment to the terminal.
**pageLimit**, means how much pages per brand you want to scrap, starting from page 1 (pageLimit=1), page 2 (pageLimit=2), page 3 (pageLimit=3), etc.

**Comment by mastershaig** [comment]
@natanelia Thank you ! I get it !

**Comment by bayaroch** [comment]
i pulled just now are u deleted your project? modules folder is gone
